NumPy_practice
* Python Library 
* Used for working with arrays
* NumPy is short for "Numerical Python"

In [2]:
import numpy as np
array= np.array([[1,2,3],
[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [3]:
print(np.__version__)

2.3.0


In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
arr2=np.array([1,2,3,4,5], ndmin=5)
print(arr2)
print(arr2.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [6]:
# indexing 
arr = np.array([1,2,3,4,5])
print(arr[1])
print(arr[2]+arr[3])

2
7


In [9]:
d2_array = np.array([[1,2,3],[4,5,6]])
print(d2_array[0,1])

d3_array = np.array([[[1,2,3],[4,5,6]],[[7,8,6],[10,11,12]]])
print(d3_array[0,1,1])


2
5


In [17]:
#Array slicing 

print(arr[-4:-1])
print(arr[0:4:2])
print(d2_array[0:2,1:3])
print(d2_array[1,0:3])

[2 3 4]
[1 3]
[[2 3]
 [5 6]]
[4 5 6]


Data Types in Numpy
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [ ]:
# data types
array = np.array([1,2,3,4,5])
print(array.dtype)

array2 = np.array(['apple', 'banana', 'cherry'])
print(array2.dtype)

int64
<U6


In [21]:
# defining a numpy array with a specific data type
arr3 = np.array([1, 2, 3, 4, 5], dtype='S')
print(arr3)

#converting data type
newarr = arr3.astype('i')
print(newarr)
print(newarr.dtype)

[b'1' b'2' b'3' b'4' b'5']
[1 2 3 4 5]
int32


In [25]:
# Numpy array copy vs view
arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr.copy() #copy is a new array
arr_view = arr.view() #view is just a view of original array
print(arr_copy)
print(arr_view)

arr_copy[0] = 10
print(arr_copy) # changes in copy does not affect original array
print(arr)

arr_view[0] = 20
print(arr_view) # changes in view affect original array
print(arr)

#to check if array owns its data or not
print(arr_copy.base) # None, arr_copy owns its data
print(arr_view.base) # arr, arr_view does not own its data, it is a view of arr

[1 2 3 4 5]
[1 2 3 4 5]
[10  2  3  4  5]
[1 2 3 4 5]
[20  2  3  4  5]
[20  2  3  4  5]
None
[20  2  3  4  5]


In [26]:
# shape of an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) # (2, 3)
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape) # (5,)

(2, 3)
(5,)


In [27]:
# reshaping an array

arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

print(arr.reshape(2,3).base) # to check if the returned array is a copy or a view, if base is not None then it is a view, if base is None then it is a copy

#Flattening an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten()
print(flat_arr)

#or using reshape 
arr= np.array([[1, 2, 3], [4, 5, 6]])
new_arr = arr.reshape(-1)
print(new_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [31]:
# array iteration
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array will go through each row
for x in arr:
    print(x)

for x in arr:
    for y in x:
        print(y)

arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) #3D array it will go through all the 2D arrays
for x in arr2:
    print(x)

for x in arr2:
    for y in x:
        for z in y:
            print(z)

[1 2 3]
[4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# iterating with nditer()
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(arr):     #nditer() is a function that allows us to iterate through an array element by element, regardless of the number of dimensions
    print(x)


# iterating with ndenumerate()
arr = np.array([[1, 2, 3], [4, 5, 6]])
for idx, x in np.ndenumerate(arr): # ndenumerate() is a function that allows us to iterate through an array element by element, and also gives us the index of the element
    print(idx, x)


# iterating with different data types
arr = np.array([1, 2, 3], dtype='S')
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']): # flags=['buffered'] is used to allow us to iterate through an array with a different data
    print(x)

# iterating with different step size
arr = np.array([1, 2, 3, 4, 5])
for x in np.nditer(arr[::2]): # to iterate through an array with a different step size
    print(x)

1
2
3
4
5
6
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
1
3
5


In [36]:
# joining arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2)) # to join two arrays
print(arr3)

arr4 = np.array([[1, 2], [3, 4]])
arr5 = np.array([[5, 6], [7, 8]])
arr6 = np.concatenate((arr4, arr5), axis=1) # to join two 2D arrays along columns
print(arr6)

arr7 = np.array([[1, 2], [3, 4]])
arr8 = np.array([[5, 6], [7, 8]])
arr9 = np.concatenate((arr7, arr8), axis=0) # to join two 2D arrays along rows
print(arr9)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
# joining arrays using stack() function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])  
arr3 = np.stack((arr1, arr2), axis=0) # to join two arrays along rows
print(arr3)

arr4 = np.array([[1, 2], [3, 4]])
arr5 = np.array([[5, 6], [7, 8]])  
arr6 = np.stack((arr4, arr5), axis=1) # to join two 2D arrays along columns
print(arr6)

arr7 = np.hstack((arr4,arr5)) # to join two arrays horizontally
print(f"arr7: {arr7}")

arr8 = np.vstack((arr4,arr5)) # to join two arrays vertically
print(f"arr8: {arr8}")

arr9 = np.dstack((arr4, arr5)) # to join two 2D arrays along depth
print(f"arr9: {arr9}")

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
arr7: [[1 2 5 6]
 [3 4 7 8]]
arr8: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
arr9: [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
# splitting arrays
arr = np.array([1, 2, 3, 4, 5, 6])
arr1, arr2 = np.split(arr, 2) # to split an array into 2 parts
print(f"arr1: {arr1}")
print(f"arr2: {arr2}")

newarr = np.array_split(arr, 3) # to split an array into 3 parts
print(f"newarr: {newarr}")

newarr2 = np.array_split(arr, 4) # to split an array into 4 parts
print(f"newarr2: {newarr2}")

print(newarr2[0])
print(newarr2[1])
print(newarr2[2])
print(newarr2[3])

arr= np.array([[1, 2], [4, 5],[7, 8], [10, 11], [12, 13],[14, 15]])
arr1, arr2,arr3 = np.split(arr, 3) # to split a 2D array into 3 parts
print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"arr3: {arr3}")


arr1: [1 2 3]
arr2: [4 5 6]
newarr: [array([1, 2]), array([3, 4]), array([5, 6])]
newarr2: [array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5]
[6]
arr1: [[1 2]
 [4 5]]
arr2: [[ 7  8]
 [10 11]]
arr3: [[12 13]
 [14 15]]


In [49]:
# searching arrays
arr = np.array([1, 2, 3, 4,3, 5,8,10,6,7,8,9])
x = np.where(arr == 3) # to search for the index of an element in an array
print(x)

y = np.where(arr % 2 == 0) # to search for the index of even numbers in an array
print(y)



(array([2, 4]),)
(array([ 1,  3,  6,  7,  8, 10]),)


In [54]:
# searchsorted() function is used to find the index where an element should be inserted to maintain the order of the array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = np.searchsorted(arr, 3) # to find the index where 3 should be inserted to maintain the order of the array
print(x)

y= np.searchsorted(arr,3,side="right")
print(y)

#multiple searchsorted() functions
z=np.searchsorted(arr,[3,6,9])
print(z)


2
3
[2 5 8]


In [58]:
# sorting arrays
arr = np.array([3, 2, 0, 1])
print(np.sort(arr)) # to sort an array

arr2 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr2)) # to sort an array of strings

arr3 = np.array([True, False, True])
print(np.sort(arr3)) # to sort an array of boolean values, False will come before

arr4= np.array([[3, 2, 0], [1, 4, 5]])
print(np.sort(arr4)) # to sort a 2D array along the last axis
print(np.sort(arr4, axis=0)) # to sort a 2D array along columns
print(np.sort(arr4, axis=1)) # to sort a 2D array along rows

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[0 2 3]
 [1 4 5]]
[[1 2 0]
 [3 4 5]]
[[0 2 3]
 [1 4 5]]


In [61]:
# filtering arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = arr[arr > 5] # to filter an array
print(x)

arr2 = np.array([41,42,43,44,45,46,47,48,49,50])
y=[True,False,True,False,True,False,True,False,True,False]
newarr = arr2[y] # to filter an array using a boolean array
print(newarr)


filter_arr=[]
for i in arr2:
    if i%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(filter_arr)
newarr2 = arr2[filter_arr] # to filter an array using a boolean array
print(newarr2)


[ 6  7  8  9 10]
[41 43 45 47 49]
[False, True, False, True, False, True, False, True, False, True]
[42 44 46 48 50]


Pseudo random number : random numbers generated through a gneration algotrithm 

In [64]:
from numpy import random
x = random.randint(100) # to generate a random integer from 0 to 100
print(x)

y=random.rand() # to generate a random float from 0 to 1
print(y)

z= random.randint(100, size=(5)) # to generate an array of 5 random integers from 0 to 100
print(z)

g=random.randint(100, size=(3, 4)) # to generate a 2D array of random integers from 0 to 100
print(g)

h = random.rand(3, 4) # to generate a 2D array of random floats from 0 to 1
print(h)

i = random.choice([3, 5, 7, 9]) # to generate a random element from a given array
print(i)

j = random.choice([3, 5, 7, 9], size=(3, 4)) # to generate a 2D array of random elements from a given array
print(j)

0
0.28462699581438244
[28 22 87 53 19]
[[52 36 22 46]
 [52  7 35 26]
 [ 0 85 68 24]]
[[0.24696341 0.84714864 0.64951232 0.04052966]
 [0.103938   0.45364336 0.38741518 0.75934862]
 [0.40931384 0.58284986 0.39683504 0.42595651]]
3
[[3 7 7 7]
 [5 3 3 5]
 [3 5 5 9]]


In [67]:
# Random Distribution
x= random.choice([3,4,5,6,7,8,9], p=[0.1,0.2,0.3,0.1,0.1,0.1,0.1], size=(10)) # to generate a random element from a given array with a given probability
print(x)
# sum of probabilities should be 1, if not it will be normalized so that the sum of probabilities is 1

y= random.choice([3,4,5,6,7,8,9], p=[0.1,0.2,0.3,0.1,0.1,0.1,0.1], size=(3,2)) # to generate a random element from a given array with a given probability
print(y)

[3 3 4 5 5 5 5 7 6 3]
[[5 5]
 [5 7]
 [4 5]]


In [ ]:
# permutation or shuffling an array 
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr) # to shuffle an array
print(arr)
# shuffle method makes changes in original array

print(random.permutation(arr)) # to permute an array, it returns a new array, original array is not changed

[3 2 5 4 1]
[1 3 5 4 2]


ufuncs : universal functions and they are NumPy functions that operate on the ndarray object

they are used to implement vectorization in numpy which is way faster than iterating over elements 

In [69]:
x= [1,2,3,4,5]
y= [1,2,3,4,5]
z=np.add(x,y) # to add two arrays element-wise
print(z)



[ 2  4  6  8 10]


# to create our own ufunc 
The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (arrays).
outputs - the number of output arrays.

In [70]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [71]:
# to check if the function is ufunc or not
print(type(myadd))


<class 'numpy.ufunc'>


In [74]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

add = np.add(arr1, arr2) # to add two arrays element-wise
print(f"add: {add}")

newarr2 = np.subtract(arr1, arr2) # to subtract two arrays element-wise
print(f"subtract: {newarr2}")

newarr3 = np.multiply(arr1, arr2) # to multiply two arrays element-wise
print(f"multiply: {newarr3}")

newarr4 = np.divide(arr1, arr2) # to divide two arrays element-wise
print(f"divide: {newarr4}")     

newarr5 = np.mod(arr1, arr2) # to find the modulus of two arrays element-wise
print(f"modulus: {newarr5}")

newarr6 = np.power(arr1, arr2) # to find the power of two arrays element-wise
print(f"power: {newarr6}")  

newarr7 = np.remainder(arr1, arr2) # to find the remainder of two arrays element-wise , same as modulus
print(f"remainder: {newarr7}")

newarr9 = np.divmod(arr1, arr2) # to find the quotient and remainder of two arrays element-wise
print(f"divmod: {newarr9}")

arr3= np.array([1, -2, -3, 4, 5])
newarr10 = np.absolute(arr3) # to find the absolute value of an array element-wise
print(f"absolute: {newarr10}")

add: [30 32 34 36 38 40]
subtract: [-10 -10 -10 -10 -10 -10]
multiply: [200 231 264 299 336 375]
divide: [0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
modulus: [10 11 12 13 14 15]
power: [ 7766279631452241920  3105570700629903195  5729018530666381312
 -4649523274362944347 -1849127232522420224  1824414961309619599]
remainder: [10 11 12 13 14 15]
divmod: (array([0, 0, 0, 0, 0, 0]), array([10, 11, 12, 13, 14, 15]))
absolute: [1 2 3 4 5]


#Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

truncation
fix
rounding
floor
ceil


In [75]:
arr = np.trunc([-3.1666, 3.6667]) # to truncate the decimal part of an array element-wise
print(f"trunc: {arr}")

arr = np.fix([-3.1666, 3.6667]) # to round an array element-wise to the nearest integer towards zero
print(f"fix: {arr}")

arr = np.ceil([-3.1666, 3.6667]) # to round an array element-wise to the nearest integer towards positive infinity
print(f"ceil: {arr}")

arr = np.floor([-3.1666, 3.6667]) # to round an array element-wise to the nearest integer towards negative infinity
print(f"floor: {arr}")

arr = np.around(3.1666, 2) # function increments preceding digit or decimal by 1 if >=5 else do nothing
print(arr)

trunc: [-3.  3.]
fix: [-3.  3.]
ceil: [-3.  4.]
floor: [-4.  3.]
3.17


In [78]:
arr = np.arange(1, 10)

print(np.log2(arr))
print(np.log10(arr))
print(np.log(arr)) # to find the natural logarithm of an array element-wise

# for log at any base
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(2, 10))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
0.30102999566398114


In [81]:
# numpy summations 

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)
print(f"add: {newarr}")

newarr2 = np.sum((arr1, arr2)) # to find the sum of two arrays element-wise
print(f"sum: {newarr2}")

newarr3 = np.sum((arr1, arr2), axis=1) # to find the sum of two arrays along rows
print(f"sum along rows: {newarr3}")

newarr4 = np.sum((arr1, arr2), axis=0) # to find the sum of two arrays along columns
print(f"sum along columns: {newarr4}")

newarr5 = np.cumsum(arr1) # to find the cumulative sum of an array
print(f"cumulative sum: {newarr5}")


add: [2 4 6]
sum: 12
sum along rows: [6 6]
sum along columns: [2 4 6]
cumulative sum: [1 3 6]


In [82]:
# products
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

arr2 = np.array([4,5,6,7])

y=np.prod([arr,arr2]) # to find the product of two arrays element-wise
print(y)

z= np.prod([arr,arr2], axis=0) # to find the product of two arrays along columns
print(z)

h= np.prod([arr,arr2], axis=1) # to find the product of two arrays along rows
print(h)

i= np.cumprod(arr) # to find the cumulative product of an array
print(i)


24
20160
[ 4 10 18 28]
[ 24 840]
[ 1  2  6 24]


In [83]:
# differences 
arr = np.array([1, 2, 4, 7, 0])
x = np.diff(arr) # to find the difference between consecutive elements of an array
print(x)

y = np.diff(arr, n=2) # to find the difference between consecutive elements of an array, n is the number of times to find the difference
print(y)



[ 1  2  3 -7]
[  1   1 -10]


In [85]:
#Lowest common multiple (LCM)
arr1 = np.array([4, 6, 8])
arr2 = np.array([12, 15, 20])
lcm = np.lcm(arr1, arr2) # to find the least common multiple of two arrays element-wise
print(lcm)

num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)

arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr) # to find the least common multiple of an array, it reduces the array to a single value by applying the lcm function cumulatively to the elements of the array
print(x)

[12 30 40]
12
18


In [86]:
# Greatest common divisor (GCD)
arr1 = np.array([4, 6, 8])
x=np.gcd.reduce(arr1) # to find the greatest common divisor of an array, it reduces the array to a single value by applying the gcd function cumulatively to the elements of the array
print(x)

2


In [87]:
#Numpy LCM and GCD functions can also be used with scalars
x = np.lcm(4, 6) # to find the least common multiple of two scalars
print(x)

y = np.gcd(4, 6) # to find the greatest common divisor of two scalars
print(y)


12
2


In [88]:
#set opertions
arr= np.array([1, 1, 2, 3, 3, 2, 3, 4, 5])
x=np.unique(arr)
print(f"unique elements: {x}")

arr1= np.array([1, 2, 3, 4, 5])
arr2= np.array([4, 5, 6, 7, 8])

newarr1 = np.intersect1d(arr1, arr2) # to find the intersection of two arrays
print(f"intersection: {newarr1}")

newarr2 = np.union1d(arr1, arr2) # to find the union of two arrays
print(f"union: {newarr2}")

newarr3 = np.setdiff1d(arr1, arr2) # to find the difference of two arrays
print(f"difference: {newarr3}") 

newarr4 = np.setxor1d(arr1, arr2) # to find the symmetric difference of two arrays
print(f"symmetric difference: {newarr4}")



unique elements: [1 2 3 4 5]
intersection: [4 5]
union: [1 2 3 4 5 6 7 8]
difference: [1 2 3]
symmetric difference: [1 2 3 6 7 8]
